### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by Huwenzhi** [jikun2008/YisingleMarkerView#2]
好像点击事件无效啊不能点

**Comment by jikun2008** [comment]
可以的  因为 这个infoWindow 其实就是一个marker  你可能 是设置的amap的点击事件

**Comment by jikun2008** [comment]
已经解决

**Comment by yzhatsy** [comment]
请问是怎么解决的，我运行这个项目，info window里的view都没有点击事件响应
