### ISSUE TITLE
快速点击获取地图位置绘制会有空指针

### ISSUE THREAD

**Issue by Auto-Tifou** [jikun2008/YisingleMarkerView#3]
具体报错如下：Attempt to invoke virtual method 'com.amap.api.maps.model.LatLng com.amap.api.maps.model.Marker.getPosition()' on a null object reference

在AbstractMarkerView.java:428这里报出。

**Comment by jikun2008** [comment]
已修复

**Comment by Auto-Tifou** [comment]
好的，谢谢您，请问下那我项目是要重新导入依赖吗还是自动会修复好？

**Comment by jikun2008** [comment]
你更新下版本号1.0.5就可以了



---原始邮件---
发件人: "liu968"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上7:24
收件人: "jikun2008/YisingleMarkerView"<YisingleMarkerView@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"jikun2008"<j314815101@qq.com&gt;;
主题: Re: [jikun2008/YisingleMarkerView] 快速点击获取地图位置绘制会有空指针 (#3)




 
好的，谢谢您，请问下那我项目是要重新导入依赖吗还是自动会修复好？

**Comment by Auto-Tifou** [comment]
好的，谢谢您
