### ISSUE TITLE
ViewHolderImpl中的setOnClickListener无响应

### ISSUE THREAD

**Issue by yzhatsy** [jikun2008/YisingleMarkerView#6]
显示多个的infowindow里layout是一个复杂的布局，设置点击监听时调用ViewHolderImpl中的setOnClickListener无响应，不知道怎么回事，能解答下吗？

**Comment by jikun2008** [comment]
布局的点击事件是不能响应的。  因为 布局是生成了一个bitmap 添加到marker上 所以。 只能响应marker的点击事件
