### ISSUE TITLE
抽象静态内部类Kotlin里怎么实现啊，就这一段

### ISSUE THREAD

**Issue by YancyHsu** [jikun2008/YisingleMarkerView#7]
大神，这一段Kotlin里怎么实现能提点下吗

        startPointMarkerView.bindInfoWindowView(new BaseMarkerView.BaseInfoWindowView<String>(R.layout.info_window, "start") {
            @Override
            public void bindData(MapInfoWindowViewHolder viewHolder, String data) {
                viewHolder.setText(R.id.tvInfoWindow, data);
            }
        });

**Comment by jikun2008** [comment]
这个麻烦自己实现了哈
